module.exports = {
  apps: [
    {
      name: "ava-backend",
      script: "npx",
      args: "tsx src/index.ts",
      cwd: "/root/projects/voice-outreach-demo/backend",
      env: {
        NODE_ENV: "production",
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/var/log/ava-backend-error.log",
      out_file: "/var/log/ava-backend-out.log",
      merge_logs: true,
      max_memory_restart: "512M",
    },
    {
      name: "ava-frontend",
      script: "npm",
      args: "start",
      cwd: "/root/projects/voice-outreach-demo/frontend",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "/var/log/ava-frontend-error.log",
      out_file: "/var/log/ava-frontend-out.log",
      merge_logs: true,
      max_memory_restart: "256M",
    },
  ],
};
